# Generated by Django 4.0.4 on 2022-05-28 03:53

import AppPeliculas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('anio', models.IntegerField()),
                ('resumen', models.TextField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to=AppPeliculas.models.ruta)),
            ],
        ),
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=40)),
                ('puntuacion', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('sexo', models.CharField(max_length=8)),
                ('mail', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=AppPeliculas.models.ruta)),
            ],
        ),
    ]
