# Generated by Django 4.0.4 on 2022-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliculas', '0002_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenia',
            name='comentario',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
