# Generated by Django 4.0.4 on 2022-05-28 12:00

import AppPeliculas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliculas', '0003_resenia_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=20)),
                ('anio_inicio', models.IntegerField()),
                ('anio_finalizacion', models.IntegerField()),
                ('temporadas', models.IntegerField()),
                ('resumen', models.TextField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to=AppPeliculas.models.ruta)),
            ],
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='resenia',
            name='pelicula',
            field=models.CharField(max_length=60),
        ),
    ]
