# Generated by Django 4.0.4 on 2022-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliculas', '0004_serie_alter_pelicula_genero_alter_pelicula_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenia',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
