# Generated by Django 4.0.4 on 2022-05-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliculas', '0005_alter_resenia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenia',
            name='puntuacion',
            field=models.CharField(max_length=20),
        ),
    ]
